spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stock_and_shipment_manager
    username: root
    password: AWVabcdefg2326222
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
  jpa:
    open-in-view: false
  devtools:
      restart:
        enabled: true
        additional-paths: src/main/java,src/main/resources/static,src/main/resources/templates
server:
  port: 80